DEBUG REMOTE: Received key event: {'key': 'c', 'action': 'down'}
DEBUG REMOTE: Received key event: {'key': 'c', 'action': 'up'}
DEBUG REMOTE: Received key event: {'key': 'control', 'action': 'down'}
DEBUG REMOTE: Received key event: {'key': 'c', 'action': 'down'}
DEBUG REMOTE: Received key event: {'key': 'control', 'action': 'up'}
DEBUG REMOTE: Received key event: {'key': 'c', 'action': 'up'}
DEBUG REMOTE: Received key event: {'key': 'control', 'action': 'down'}
DEBUG REMOTE: Received key event: {'key': 'x', 'action': 'down'}
DEBUG REMOTE: Received key event: {'key': 'control', 'action': 'up'}
DEBUG REMOTE: Received key event: {'key': 'x', 'action': 'up'}
DEBUG REMOTE: Received key event: {'key': 'control', 'action': 'down'}
DEBUG REMOTE: Received key event: {'key': 'c', 'action': 'down'}
DEBUG REMOTE: Received key event: {'key': 'control', 'action': 'up'}
